### ISSUE TITLE
Highlighting is matching some keywords in HTML plain text

### ISSUE THREAD

**Issue by stephenjjbrown** [GerardSmit/vscode-webforms#1]
If I place code such as:

```html
<head runat="server">
    <title>is checked<title>
</head>
```

Both the word "is" and "checked" are being highlighted. I imagine it's because those are keywords in C#? C# keywords should only highlighted if in a code block surrounded by <% %>

**Comment by GerardSmit** [comment]
I can't reproduce this problem.

When targeting the language "HTML" the words `is` and `checked` are only highlighted in code blocks:

![image](https://user-images.githubusercontent.com/2109929/138070366-98a41b1b-f95f-4170-a825-6614fe7b5db9.png)

---

Are you sure these highlights are coming from this extension? You can check this by setting your cursor in the word (e.g. `i|s`), press F1 (Show all commands) and search for "Developer: Inspect Editor Tokens and Scopes":

![image](https://user-images.githubusercontent.com/2109929/138070751-b307a1c6-d91a-4b45-8761-770431e02e39.png)

A pop-up will show with information about the tokens under the cursor. In my case, the textmate scope is `text.html.derivate`:

![image](https://user-images.githubusercontent.com/2109929/138071129-b04a372d-3056-4a6e-8be5-c75c331bf311.png)

When checking `is` in the code block it should be overridden by `source.cs-embedded` which is provided by this extension:

![image](https://user-images.githubusercontent.com/2109929/138071223-447d5b56-92d4-4027-9b2f-039174cf579d.png)

**Comment by stephenjjbrown** [comment]
I have since switched to a different machine and haven't been able to reproduce it. You're probably right in that it was likely another extension interfering.

Great plugin btw! Really useful for those of use who still need to use Web Forms on a regular basis.
